#spring:
#  security:
#    user:
#      # 修改默认用户名密码信息
#      name: admin
#      password: admin
#      roles: ['admin','user']
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl