version: '3.1'
services:
  mysql-db:
    # 指定容器的名称
    container_name: mysql
    # 指定镜像和版本
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    restart: always
    environment:
      # 配置root密码
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      # 挂载数据目录
      - "/root/mysql/data:/var/lib/mysql"
      # 挂载配置文件目录
      - "/root/mysql/config:/etc/mysql/conf.d"
  redis:
    image: redis:latest
    restart: always
    hostname: redis
    container_name: redis
    privileged: true
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/usr/local/redis/data
      - ./conf/redis.conf:/usr/local/redis/conf/redis.conf
      - ./logs:/usr/local/redis/logs